begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  full_name text,
  is_active boolean not null default true,
  is_paid boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tests (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text,
  access_type text not null check (access_type in ('demo', 'paid')),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.recordings (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.tests (id) on delete cascade,
  title text,
  wpm integer not null check (wpm > 0),
  audio_url text not null,
  reference_transcript text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (test_id, wpm)
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  recording_id bigint not null references public.recordings (id) on delete cascade,
  submitted_transcript text not null,
  accuracy numeric(5, 2) not null check (accuracy >= 0 and accuracy <= 100),
  matched_words integer not null default 0 check (matched_words >= 0),
  reference_word_count integer not null default 0 check (reference_word_count >= 0),
  submitted_word_count integer not null default 0 check (submitted_word_count >= 0),
  mistake_count integer not null default 0 check (mistake_count >= 0),
  mistake_details jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists recordings_test_id_idx on public.recordings (test_id);
create index if not exists attempts_user_id_created_at_idx on public.attempts (user_id, created_at desc);
create index if not exists attempts_recording_id_idx on public.attempts (recording_id);

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger set_tests_updated_at
before update on public.tests
for each row execute function public.set_updated_at();

create trigger set_recordings_updated_at
before update on public.recordings
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = coalesce(public.profiles.full_name, excluded.full_name);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user_profile();

alter table public.profiles enable row level security;
alter table public.tests enable row level security;
alter table public.recordings enable row level security;
alter table public.attempts enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (
  auth.uid() = id
  and is_active = true
);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (
  auth.uid() = id
  and is_active = true
  and is_paid = false
  and email = auth.email()
);

drop policy if exists "tests_select_accessible" on public.tests;
create policy "tests_select_accessible"
on public.tests
for select
to authenticated
using (
  is_active
  and exists (
    select 1
    from public.profiles profile
    where profile.id = auth.uid()
      and profile.is_active
      and (public.tests.access_type = 'demo' or profile.is_paid)
  )
);

drop policy if exists "recordings_select_accessible" on public.recordings;
create policy "recordings_select_accessible"
on public.recordings
for select
to authenticated
using (
  is_active
  and exists (
    select 1
    from public.tests test
    join public.profiles profile on profile.id = auth.uid()
    where test.id = public.recordings.test_id
      and test.is_active
      and profile.is_active
      and (test.access_type = 'demo' or profile.is_paid)
  )
);

drop policy if exists "attempts_select_own" on public.attempts;
create policy "attempts_select_own"
on public.attempts
for select
to authenticated
using (
  auth.uid() = user_id
  and exists (
    select 1
    from public.profiles profile
    where profile.id = auth.uid()
      and profile.is_active
  )
);

drop policy if exists "attempts_insert_own" on public.attempts;
create policy "attempts_insert_own"
on public.attempts
for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.profiles profile
    join public.recordings recording on recording.id = public.attempts.recording_id
    join public.tests test on test.id = recording.test_id
    where profile.id = auth.uid()
      and profile.is_active
      and recording.is_active
      and test.is_active
      and (test.access_type = 'demo' or profile.is_paid)
  )
);

commit;
